### ISSUE TITLE
Search in joined table

### ISSUE THREAD

**Issue by freshface** [marcelgwerder/laravel-api-handler#44]
I need to search in a joined column **name** field.
By default it searches in the main table, can I change this so it searches in `products_content.name=Test` instead of `products.name`

**Comment by marcelgwerder** [comment]
Nope, not yet. All you can do right now is adding the "custom" filter to the query builder yourself after the rest was applied. You can use the `getBuilder` method after calling `parseSingle`/`parseMultiple` to get started.

I'm thinking about a more powerful way to query the data for version 1.0 of the package. 
The current approach of filtering is very limited because of the fact that the filter statements are divided in multiple get params and also due to the limitation of parameter key naming. Im not yet past conceptual work though because of very limited time available for the project.

**Comment by freshface** [comment]
Hi marcelgwerder  

Thanks for the fast reply.
Would be nice to have in v1.0

Kinda new to laravel, is there an example available on how to add the custom filter?

**Comment by marcelgwerder** [comment]
What you'll get with `getBuilder` is a query builder object and you'll thus have all the tools available described in the respective section of the Laravel docs: [Database: Query Builder](https://laravel.com/docs/5.4/queries).

You may have to pass the get parameters to the api handler manually because it will otherwise try to add the custom filter it to the query of the main table. There is a convenient `except` method on the request object. How you can pass the params manually is documented in the readme of the package.

**Comment by freshface** [comment]
Hi

I am almost there

```
 $builder = ApiHandler::parseMultiple($query)->getBuilder();
        $queryBuilder = $builder->getQuery();
        $queryBuilder->where('project_content.name', 'like', 'Green%');
```

On thing I don't get is how you would use the `except` method.
Any of tips`/

**Comment by marcelgwerder** [comment]
You can use the [request object](https://laravel.com/docs/5.4/requests#accessing-the-request) to access the get params:

```php
public function index(Request $request) 
{
    // ...
    $builder = ApiHandler::parseMultiple($query, [], $request->except('project_content_name'))->getBuilder();
    if ($request->has('project_content_name')) {
        $queryBuilder = $builder->getQuery();
        $queryBuilder->where('project_content.name', 'like', $request->input('project_content_name').'%');
    }
    // ...
}
```

The `getQuery` call should actually not be possible as far as I remember because the `EloquentBuilder` should pass all calls to the `QueryBuilder` automatically.

**Comment by freshface** [comment]
Hi

When I do it like this `http://nanopixel-dashboard.local:8888/api/projects?_config=meta-total-count,meta-filter-count&id=3&project_content_name=f`

It still tries to access project.project_content_name:

```
{
    "message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project.project_content_name' in 'where clause' (SQL: select count(*) as aggregate from `project` left join `project_content` on `project_content`.`project_id` = `project`.`id` where `project`.`id` = 3 and `project_content`.`name` like %f% and `project`.`id` = 3 and `project`.`project_content_name` = f)",
    "code": "42S22",
    "status_code": 500
}
```

The `$request->except('project_content_name')` doesn't seem to be ignored.

```
 $builder = ApiHandler::parseMultiple($query, [], $request->except('project_content_name'))->getBuilder();
        //$queryBuilder = $builder->getQuery();

        if ($request->has('project_content_name')) {
            $builder->where('project_content.name', 'like', '%' . $request->input('project_content_name') . '%');
        }

```

**Comment by freshface** [comment]
Never mind, I found the problem.
I had another `ApiHandler::parseMultiple()` which  I overlooked.

**Comment by freshface** [comment]
Another problem with this solution, the meta information gets lost when I do it like this, its an empty array.

```
 $builder = ApiHandler::parseMultiple($query, [], $request->except(['content_name', 'content_language']))->getBuilder();

        // This is a fix to search in other tables.
        if ($request->has('content_name')) {
            $builder->where('project_content.name', 'like', '%' . $request->input('content_name') . '%');
        }

         if ($request->has('content_language')) {
            $builder->where('project_content.language', '=', $request->input('content_language'));
        }

        return $builder->get();

```

**Comment by freshface** [comment]
Okay, found it...


```
 $query = Project::GetWithContent();


          // This is a fix to search in other tables.
        if ($request->has('content_name')) {
            $query->where('project_content.name', 'like', '%' . $request->input('content_name') . '%');
        }

         if ($request->has('content_language')) {
            $query->where('project_content.language', '=', $request->input('content_language'));
        }

        $result = ApiHandler::parseMultiple($query, [], $request->except(['content_name', 'content_language']));
        return $result->getResponse(); 

```

**Comment by bemonio** [comment]
Hi!, sorry for reopen it. are there a method to solve the problem with meta information?
